'use strict';

require('dotenv').config();
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const books = [
  // ── Self Help ─────────────────────────────────────────────────────────────
  {
    title: 'Atomic Habits',
    author: 'James Clear',
    category: 'Self Help',
    genre: 'Self Development',
    description: 'An easy and proven way to build good habits and break bad ones. Tiny changes, remarkable results.',
    price: 499, stock: 50, publishedBy: 'Penguin Random House', language: 'English',
    imageUrl: '/images/atomic-habits.jpg', rating: 4.8,
  },
  {
    title: 'Deep Work',
    author: 'Cal Newport',
    category: 'Self Help',
    genre: 'Productivity',
    description: 'Rules for focused success in a distracted world.',
    price: 449, stock: 40, publishedBy: 'Grand Central Publishing', language: 'English',
    imageUrl: '/images/deep-work.jpg', rating: 4.5,
  },
  {
    title: 'The Subtle Art of Not Giving a F*ck',
    author: 'Mark Manson',
    category: 'Self Help',
    genre: 'Self Development',
    description: 'A counterintuitive approach to living a good life.',
    price: 379, stock: 38, publishedBy: 'HarperOne', language: 'English',
    imageUrl: '/images/subtle-art.jpg', rating: 4.1,
  },
  {
    title: 'Ikigai: The Japanese Secret to a Long and Happy Life',
    author: 'Héctor García & Francesc Miralles',
    category: 'Self Help',
    genre: 'Lifestyle',
    description: 'Unlock your purpose and find fulfillment in the Japanese philosophy of Ikigai.',
    price: 279, stock: 55, publishedBy: 'Penguin Books', language: 'English',
    imageUrl: '/images/ikigai.jpg', rating: 4.3,
  },
  {
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    category: 'Self Help',
    genre: 'Success',
    description: 'The classic bestseller on the philosophy of personal achievement.',
    price: 199, stock: 65, publishedBy: 'Sound Wisdom', language: 'English',
    imageUrl: '/images/think-and-grow-rich.jpg', rating: 3.9,
  },
  {
    title: 'The Power of Now',
    author: 'Eckhart Tolle',
    category: 'Self Help',
    genre: 'Mindfulness',
    description: 'A guide to spiritual enlightenment through present-moment awareness.',
    price: 350, stock: 45, publishedBy: 'New World Library', language: 'English',
    imageUrl: '/images/power-of-now.jpg', rating: 4.6,
  },
  {
    title: 'Can\'t Hurt Me',
    author: 'David Goggins',
    category: 'Self Help',
    genre: 'Motivation',
    description: 'Master your mind and defy the odds. A story of resilience and mental toughness.',
    price: 520, stock: 30, publishedBy: 'Lioncrest Publishing', language: 'English',
    imageUrl: '/images/cant-hurt-me.jpg', rating: 4.7,
  },
  {
    title: 'The 5 AM Club',
    author: 'Robin Sharma',
    category: 'Self Help',
    genre: 'Productivity',
    description: 'Own your morning, elevate your life. The morning routine of world-class performers.',
    price: 399, stock: 50, publishedBy: 'HarperCollins', language: 'English',
    imageUrl: '/images/5am-club.jpg', rating: 4.0,
  },
  {
    title: 'You Can Heal Your Life',
    author: 'Louise Hay',
    category: 'Self Help',
    genre: 'Wellness',
    description: 'Discover the power of affirmations and how your thoughts shape your life.',
    price: 299, stock: 40, publishedBy: 'Hay House', language: 'English',
    imageUrl: '/images/you-can-heal.jpg', rating: 4.4,
  },
  {
    title: 'The 7 Habits of Highly Effective People',
    author: 'Stephen R. Covey',
    category: 'Self Help',
    genre: 'Personal Effectiveness',
    description: 'Powerful lessons in personal change. A foundational framework for success.',
    price: 449, stock: 35, publishedBy: 'Simon & Schuster', language: 'English',
    imageUrl: '/images/7-habits.jpg', rating: 4.5,
  },

  // ── Finance ────────────────────────────────────────────────────────────────
  {
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    category: 'Finance',
    genre: 'Personal Finance',
    description: 'Timeless lessons on wealth, greed, and happiness.',
    price: 399, stock: 35, publishedBy: 'Jaico Publishing House', language: 'English',
    imageUrl: '/images/psychology-of-money.jpg', rating: 4.7,
  },
  {
    title: 'Rich Dad Poor Dad',
    author: 'Robert T. Kiyosaki',
    category: 'Finance',
    genre: 'Personal Finance',
    description: 'What the rich teach their kids about money that the poor and middle class do not.',
    price: 349, stock: 45, publishedBy: 'Plata Publishing', language: 'English',
    imageUrl: '/images/rich-dad-poor-dad.jpg', rating: 4.0,
  },
  {
    title: 'The Intelligent Investor',
    author: 'Benjamin Graham',
    category: 'Finance',
    genre: 'Investing',
    description: 'The definitive book on value investing. A must-read for every investor.',
    price: 599, stock: 25, publishedBy: 'HarperBusiness', language: 'English',
    imageUrl: '/images/intelligent-investor.jpg', rating: 4.8,
  },
  {
    title: 'Let\'s Talk Money',
    author: 'Monika Halan',
    category: 'Finance',
    genre: 'Personal Finance',
    description: 'Your guide to a life free from financial worries. Perfect for Indian readers.',
    price: 299, stock: 60, publishedBy: 'HarperCollins India', language: 'English',
    imageUrl: '/images/lets-talk-money.jpg', rating: 4.5,
  },
  {
    title: 'Coffee Can Investing',
    author: 'Saurabh Mukherjea',
    category: 'Finance',
    genre: 'Investing',
    description: 'The low-risk road to stupendous wealth. Learn the coffee can portfolio approach.',
    price: 499, stock: 30, publishedBy: 'Portfolio Penguin', language: 'English',
    imageUrl: '/images/coffee-can.jpg', rating: 4.3,
  },

  // ── Fiction ────────────────────────────────────────────────────────────────
  {
    title: '1984',
    author: 'George Orwell',
    category: 'Fiction',
    genre: 'Dystopian Fiction',
    description: 'A chilling prophecy about the future. A masterpiece about totalitarianism.',
    price: 249, stock: 70, publishedBy: 'Secker & Warburg', language: 'English',
    imageUrl: '/images/1984.jpg', rating: 4.7,
  },
  {
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    category: 'Fiction',
    genre: 'Philosophical Fiction',
    description: 'A magical story about following your dreams.',
    price: 299, stock: 60, publishedBy: 'HarperOne', language: 'English',
    imageUrl: '/images/the-alchemist.jpg', rating: 4.2,
  },
  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    category: 'Fiction',
    genre: 'Classic Fiction',
    description: 'A gripping tale of racial injustice and moral growth in the American South.',
    price: 299, stock: 50, publishedBy: 'J. B. Lippincott & Co.', language: 'English',
    imageUrl: '/images/to-kill-mockingbird.jpg', rating: 4.8,
  },
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    category: 'Fiction',
    genre: 'Classic Fiction',
    description: 'A portrait of the Jazz Age and the decay of the American Dream.',
    price: 199, stock: 55, publishedBy: 'Scribner', language: 'English',
    imageUrl: '/images/great-gatsby.jpg', rating: 4.4,
  },
  {
    title: 'Harry Potter and the Philosopher\'s Stone',
    author: 'J.K. Rowling',
    category: 'Fiction',
    genre: 'Fantasy',
    description: 'The magical beginning of Harry Potter\'s journey to Hogwarts School of Witchcraft and Wizardry.',
    price: 399, stock: 80, publishedBy: 'Bloomsbury', language: 'English',
    imageUrl: '/images/harry-potter-1.jpg', rating: 4.9,
  },
  {
    title: 'The Kite Runner',
    author: 'Khaled Hosseini',
    category: 'Fiction',
    genre: 'Literary Fiction',
    description: 'A story of friendship, betrayal, and redemption set against the backdrop of Afghanistan.',
    price: 349, stock: 45, publishedBy: 'Riverhead Books', language: 'English',
    imageUrl: '/images/kite-runner.jpg', rating: 4.6,
  },
  {
    title: 'The Midnight Library',
    author: 'Matt Haig',
    category: 'Fiction',
    genre: 'Magical Realism',
    description: 'Between life and death there is a library. A book about infinite possibilities.',
    price: 449, stock: 35, publishedBy: 'Canongate Books', language: 'English',
    imageUrl: '/images/midnight-library.jpg', rating: 4.4,
  },
  {
    title: 'Verity',
    author: 'Colleen Hoover',
    category: 'Fiction',
    genre: 'Thriller',
    description: 'A thrilling, shocking story about a writer who uncovers a dangerous manuscript.',
    price: 399, stock: 40, publishedBy: 'Grand Central Publishing', language: 'English',
    imageUrl: '/images/verity.jpg', rating: 4.3,
  },
  {
    title: 'The God of Small Things',
    author: 'Arundhati Roy',
    category: 'Fiction',
    genre: 'Literary Fiction',
    description: 'A story about the tragic effects of the caste system in Kerala, India.',
    price: 349, stock: 30, publishedBy: 'IndiaInk', language: 'English',
    imageUrl: '/images/god-of-small-things.jpg', rating: 4.4,
  },
  {
    title: 'Train to Pakistan',
    author: 'Khushwant Singh',
    category: 'Fiction',
    genre: 'Historical Fiction',
    description: 'A powerful account of the Partition of India through the eyes of a small village.',
    price: 249, stock: 40, publishedBy: 'Roli Books', language: 'English',
    imageUrl: '/images/train-to-pakistan.jpg', rating: 4.2,
  },

  // ── History ────────────────────────────────────────────────────────────────
  {
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    category: 'History',
    genre: 'Non-Fiction',
    description: 'A sweeping narrative of human history from the Stone Age to the present.',
    price: 599, stock: 30, publishedBy: 'Harper Collins', language: 'English',
    imageUrl: '/images/sapiens.jpg', rating: 4.6,
  },
  {
    title: 'India: A History',
    author: 'John Keay',
    category: 'History',
    genre: 'Indian History',
    description: 'A comprehensive history of India from ancient civilizations to independence.',
    price: 699, stock: 20, publishedBy: 'HarperCollins', language: 'English',
    imageUrl: '/images/india-history.jpg', rating: 4.4,
  },
  {
    title: 'Discovery of India',
    author: 'Jawaharlal Nehru',
    category: 'History',
    genre: 'Indian History',
    description: 'Nehru\'s classic account of Indian civilization, culture, and the independence movement.',
    price: 499, stock: 25, publishedBy: 'Penguin Books India', language: 'English',
    imageUrl: '/images/discovery-of-india.jpg', rating: 4.5,
  },
  {
    title: 'Freedom at Midnight',
    author: 'Larry Collins & Dominique Lapierre',
    category: 'History',
    genre: 'Indian History',
    description: 'A gripping account of India\'s struggle for independence and the partition.',
    price: 399, stock: 30, publishedBy: 'Vikas Publishers', language: 'English',
    imageUrl: '/images/freedom-at-midnight.jpg', rating: 4.6,
  },

  // ── Biography ──────────────────────────────────────────────────────────────
  {
    title: 'Wings of Fire',
    author: 'A.P.J. Abdul Kalam',
    category: 'Biography',
    genre: 'Autobiography',
    description: 'The autobiography of India\'s Missile Man and former President.',
    price: 299, stock: 70, publishedBy: 'Universities Press', language: 'English',
    imageUrl: '/images/wings-of-fire.jpg', rating: 4.8,
  },
  {
    title: 'My Experiments with Truth',
    author: 'Mahatma Gandhi',
    category: 'Biography',
    genre: 'Autobiography',
    description: 'The autobiography of Mahatma Gandhi — his life, principles, and philosophy.',
    price: 249, stock: 50, publishedBy: 'Navajivan Trust', language: 'English',
    imageUrl: '/images/gandhi-autobiography.jpg', rating: 4.7,
  },
  {
    title: 'Steve Jobs',
    author: 'Walter Isaacson',
    category: 'Biography',
    genre: 'Business Biography',
    description: 'The exclusive biography of Apple co-founder Steve Jobs based on interviews.',
    price: 699, stock: 25, publishedBy: 'Simon & Schuster', language: 'English',
    imageUrl: '/images/steve-jobs.jpg', rating: 4.5,
  },
  {
    title: 'Shoe Dog',
    author: 'Phil Knight',
    category: 'Biography',
    genre: 'Business Biography',
    description: 'A memoir by the creator of Nike — raw, humble, and inspiring.',
    price: 499, stock: 30, publishedBy: 'Simon & Schuster', language: 'English',
    imageUrl: '/images/shoe-dog.jpg', rating: 4.7,
  },
  {
    title: 'Long Walk to Freedom',
    author: 'Nelson Mandela',
    category: 'Biography',
    genre: 'Autobiography',
    description: 'Nelson Mandela\'s autobiography — the story of his life and the anti-apartheid movement.',
    price: 549, stock: 25, publishedBy: 'Little, Brown', language: 'English',
    imageUrl: '/images/long-walk-freedom.jpg', rating: 4.8,
  },

  // ── Spiritual & Devotional ─────────────────────────────────────────────────
  {
    title: 'Hanuman Chalisa: With Meaning & Commentary',
    author: 'Goswami Tulsidas (Commentary: Swami Ramsukhdas)',
    category: 'Spiritual',
    genre: 'Hindu Devotional',
    description: 'The sacred 40-verse hymn to Lord Hanuman with detailed Hindi and English commentary. Includes transliteration, meaning, and the significance of each verse.',
    price: 149, stock: 200, publishedBy: 'Gita Press Gorakhpur', language: 'Hindi',
    imageUrl: '/images/hanuman-chalisa.jpg', rating: 4.9,
  },
  {
    title: 'Navratri Vishesh: Maa Durga Aradhana',
    author: 'Pandit Shriram Sharma',
    category: 'Spiritual',
    genre: 'Hindu Devotional',
    description: 'A comprehensive guide to Navratri celebrations — nine nights of worship, fasting, mantras, and the glory of the nine forms of Maa Durga.',
    price: 199, stock: 150, publishedBy: 'Yug Nirman Yojana', language: 'Hindi',
    imageUrl: '/images/navratri-special.jpg', rating: 4.8,
  },
  {
    title: 'Shiv Mahima: The Glory of Lord Shiva',
    author: 'Swami Sivananda',
    category: 'Spiritual',
    genre: 'Hindu Devotional',
    description: 'Explore the infinite glory of Lord Shiva through stories, stotras, and the significance of Mahadev in Hindu scripture. Includes Shiv Mahimna Stotram.',
    price: 179, stock: 120, publishedBy: 'Divine Life Society', language: 'Hindi/English',
    imageUrl: '/images/shiv-mahima.jpg', rating: 4.9,
  },
  {
    title: 'Krishna Pujan Vidhi',
    author: 'Swami Prabhupada',
    category: 'Spiritual',
    genre: 'Hindu Devotional',
    description: 'A complete guide to Krishna worship — daily puja rituals, bhajans, mantras, and the significance of Janmashtami celebrations.',
    price: 199, stock: 180, publishedBy: 'ISKCON Publications', language: 'Hindi/English',
    imageUrl: '/images/krishna-pujan.jpg', rating: 4.8,
  },
  {
    title: 'Shri Lakshmi Arti Sangrah',
    author: 'Various Saints',
    category: 'Spiritual',
    genre: 'Hindu Devotional',
    description: 'Collection of Maa Lakshmi artis, stotrams, and chalisa. Includes Kanakdhara Stotram and Mahalakshmi Ashtakam for Friday puja.',
    price: 99, stock: 250, publishedBy: 'Gita Press Gorakhpur', language: 'Hindi',
    imageUrl: '/images/lakshmi-arti.jpg', rating: 4.9,
  },
  {
    title: 'Bhagavad Gita As It Is',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    category: 'Spiritual',
    genre: 'Hindu Scripture',
    description: 'The most widely read edition of the Bhagavad Gita with original Sanskrit, Roman transliteration, and purports.',
    price: 350, stock: 150, publishedBy: 'ISKCON Publications', language: 'English',
    imageUrl: '/images/bhagavad-gita.jpg', rating: 4.9,
  },
  {
    title: 'Ramcharitmanas',
    author: 'Goswami Tulsidas',
    category: 'Spiritual',
    genre: 'Hindu Scripture',
    description: 'The epic retelling of the Ramayana in Awadhi verse by Sant Tulsidas. A treasure of devotion and dharma.',
    price: 299, stock: 100, publishedBy: 'Gita Press Gorakhpur', language: 'Hindi',
    imageUrl: '/images/ramcharitmanas.jpg', rating: 5.0,
  },
  {
    title: 'Sundarkand: The Beautiful Chapter',
    author: 'Goswami Tulsidas',
    category: 'Spiritual',
    genre: 'Hindu Devotional',
    description: 'The fifth chapter of Ramcharitmanas celebrating Hanuman\'s leap to Lanka. Recitation is said to bring peace and remove obstacles.',
    price: 149, stock: 200, publishedBy: 'Gita Press Gorakhpur', language: 'Hindi',
    imageUrl: '/images/sundarkand.jpg', rating: 4.9,
  },
  {
    title: 'Saraswati Vandana: Prayers for Wisdom',
    author: 'Compiled by Acharya Pandit Vishnu Sharma',
    category: 'Spiritual',
    genre: 'Hindu Devotional',
    description: 'Mantras, artis and stotrams dedicated to Maa Saraswati — goddess of knowledge, music, and arts. Perfect for students and artists.',
    price: 129, stock: 180, publishedBy: 'Lotus Press', language: 'Hindi/Sanskrit',
    imageUrl: '/images/saraswati-vandana.jpg', rating: 4.7,
  },
  {
    title: 'Shrimad Bhagavatam: The Story of God',
    author: 'A.C. Bhaktivedanta Swami Prabhupada',
    category: 'Spiritual',
    genre: 'Hindu Scripture',
    description: 'The great devotional classic describing the pastimes of Lord Krishna and the path of pure devotional service.',
    price: 799, stock: 50, publishedBy: 'Bhaktivedanta Book Trust', language: 'English',
    imageUrl: '/images/shrimad-bhagavatam.jpg', rating: 4.9,
  },
  {
    title: 'In the Light of Wisdom: Sufi Teachings',
    author: 'Hazrat Inayat Khan',
    category: 'Spiritual',
    genre: 'Sufi',
    description: 'Teachings of the great Sufi mystic on love, harmony, and the divine path.',
    price: 299, stock: 40, publishedBy: 'Omega Publications', language: 'English',
    imageUrl: '/images/sufi-wisdom.jpg', rating: 4.5,
  },
  {
    title: 'The Autobiography of a Yogi',
    author: 'Paramahansa Yogananda',
    category: 'Spiritual',
    genre: 'Yoga & Meditation',
    description: 'One of the greatest spiritual classics of the 20th century. A guide to yoga philosophy and the lives of saints.',
    price: 399, stock: 80, publishedBy: 'Self-Realization Fellowship', language: 'English',
    imageUrl: '/images/autobiography-yogi.jpg', rating: 4.8,
  },

  // ── Poetry ─────────────────────────────────────────────────────────────────
  {
    title: 'Gitanjali',
    author: 'Rabindranath Tagore',
    category: 'Poetry',
    genre: 'Indian Poetry',
    description: 'Song Offerings — the Nobel Prize-winning collection of devotional poems by Tagore. A masterpiece of spiritual longing and beauty.',
    price: 199, stock: 60, publishedBy: 'Macmillan', language: 'English',
    imageUrl: '/images/gitanjali.jpg', rating: 4.8,
  },
  {
    title: 'Madhushala',
    author: 'Harivansh Rai Bachchan',
    category: 'Poetry',
    genre: 'Hindi Poetry',
    description: 'A celebrated Hindi poem where the tavern becomes a metaphor for life. One of the most iconic works in Hindi literature.',
    price: 179, stock: 70, publishedBy: 'Rajpal & Sons', language: 'Hindi',
    imageUrl: '/images/madhushala.jpg', rating: 4.9,
  },
  {
    title: 'The Waste Land and Other Poems',
    author: 'T.S. Eliot',
    category: 'Poetry',
    genre: 'Modernist Poetry',
    description: 'Landmark poems of modernism including The Waste Land, Prufrock, and The Hollow Men.',
    price: 249, stock: 30, publishedBy: 'Harvest Books', language: 'English',
    imageUrl: '/images/waste-land.jpg', rating: 4.5,
  },
  {
    title: 'Leaves of Grass',
    author: 'Walt Whitman',
    category: 'Poetry',
    genre: 'American Poetry',
    description: 'Whitman\'s masterwork — a celebration of the self, nature, and democracy.',
    price: 299, stock: 25, publishedBy: 'Dover Publications', language: 'English',
    imageUrl: '/images/leaves-of-grass.jpg', rating: 4.4,
  },
  {
    title: 'Rubaiyat of Omar Khayyam',
    author: 'Omar Khayyam (trans. Edward FitzGerald)',
    category: 'Poetry',
    genre: 'Persian Poetry',
    description: 'The timeless Persian quatrains on love, wine, and the mysteries of existence.',
    price: 199, stock: 40, publishedBy: 'Penguin Classics', language: 'English',
    imageUrl: '/images/rubaiyat.jpg', rating: 4.6,
  },
  {
    title: 'I Know Why the Caged Bird Sings (Poems)',
    author: 'Maya Angelou',
    category: 'Poetry',
    genre: 'African-American Poetry',
    description: 'Selected poems from one of America\'s most celebrated poets — powerful, lyrical, and deeply human.',
    price: 299, stock: 35, publishedBy: 'Random House', language: 'English',
    imageUrl: '/images/maya-angelou-poems.jpg', rating: 4.7,
  },
  {
    title: 'Divan-e-Ghalib',
    author: 'Mirza Ghalib',
    category: 'Poetry',
    genre: 'Urdu Poetry',
    description: 'The collected Urdu and Persian poetry of Mirza Ghalib — love, loss, philosophy, and wit in matchless couplets.',
    price: 299, stock: 50, publishedBy: 'Anjuman Taraqqi Urdu', language: 'Urdu/Hindi',
    imageUrl: '/images/ghalib.jpg', rating: 4.9,
  },
  {
    title: 'Kamayani',
    author: 'Jai Shankar Prasad',
    category: 'Poetry',
    genre: 'Hindi Epic Poetry',
    description: 'The greatest Hindi epic poem — a philosophical narrative of Manu and Shradha. A cornerstone of Chhayavad literature.',
    price: 249, stock: 30, publishedBy: 'Lokbharti Prakashan', language: 'Hindi',
    imageUrl: '/images/kamayani.jpg', rating: 4.7,
  },
  {
    title: 'Selected Poems: Gulzar',
    author: 'Gulzar',
    category: 'Poetry',
    genre: 'Hindi/Urdu Poetry',
    description: 'Evocative poetry by India\'s most beloved lyricist and poet. Profound yet simple.',
    price: 349, stock: 60, publishedBy: 'Penguin Books India', language: 'Hindi/Urdu',
    imageUrl: '/images/gulzar-poems.jpg', rating: 4.8,
  },
  {
    title: 'The Prophet',
    author: 'Kahlil Gibran',
    category: 'Poetry',
    genre: 'Philosophical Poetry',
    description: 'Timeless poetic prose on love, freedom, children, work, pain, and more.',
    price: 229, stock: 70, publishedBy: 'Alfred A. Knopf', language: 'English',
    imageUrl: '/images/the-prophet.jpg', rating: 4.8,
  },

  // ── Storytelling ───────────────────────────────────────────────────────────
  {
    title: 'Panchatantra: Ancient Indian Fables',
    author: 'Vishnu Sharma (trans. Arthur W. Ryder)',
    category: 'Storytelling',
    genre: 'Indian Fables',
    description: 'The world\'s oldest collection of animal fables that teach wisdom through storytelling. 2000-year-old tales still relevant today.',
    price: 249, stock: 80, publishedBy: 'Penguin Classics', language: 'English',
    imageUrl: '/images/panchatantra.jpg', rating: 4.7,
  },
  {
    title: 'Jataka Tales: Stories of the Buddha',
    author: 'Traditional (retold by B.S. Srinivas)',
    category: 'Storytelling',
    genre: 'Buddhist Stories',
    description: '547 stories of the Buddha\'s previous lives — fables, parables, and moral tales that have inspired generations across Asia.',
    price: 299, stock: 50, publishedBy: 'Sterling Publishers', language: 'English',
    imageUrl: '/images/jataka-tales.jpg', rating: 4.6,
  },
  {
    title: 'Malgudi Days',
    author: 'R.K. Narayan',
    category: 'Storytelling',
    genre: 'Short Stories',
    description: 'Masterful short stories set in the fictional town of Malgudi. A window into everyday Indian life with wit and warmth.',
    price: 299, stock: 45, publishedBy: 'Penguin Books India', language: 'English',
    imageUrl: '/images/malgudi-days.jpg', rating: 4.8,
  },
  {
    title: 'The Canterbury Tales',
    author: 'Geoffrey Chaucer',
    category: 'Storytelling',
    genre: 'Classic Stories',
    description: 'Chaucer\'s timeless collection of stories told by pilgrims on their way to Canterbury.',
    price: 349, stock: 25, publishedBy: 'Penguin Classics', language: 'English',
    imageUrl: '/images/canterbury-tales.jpg', rating: 4.4,
  },
  {
    title: 'Arabian Nights: One Thousand and One Nights',
    author: 'Anonymous (trans. Richard F. Burton)',
    category: 'Storytelling',
    genre: 'Folklore',
    description: 'The legendary collection of Middle Eastern folk tales told by Scheherazade to save her life.',
    price: 399, stock: 35, publishedBy: 'Penguin Classics', language: 'English',
    imageUrl: '/images/arabian-nights.jpg', rating: 4.6,
  },
  {
    title: 'Devlok with Devdutt Pattanaik',
    author: 'Devdutt Pattanaik',
    category: 'Storytelling',
    genre: 'Indian Mythology',
    description: 'Stories from Hindu mythology made accessible and relevant to modern life.',
    price: 349, stock: 60, publishedBy: 'Penguin Books India', language: 'English',
    imageUrl: '/images/devlok.jpg', rating: 4.5,
  },
  {
    title: 'Mythology: Timeless Tales of Gods and Heroes',
    author: 'Edith Hamilton',
    category: 'Storytelling',
    genre: 'Mythology',
    description: 'The classic introduction to Greek, Roman, and Norse mythology.',
    price: 349, stock: 30, publishedBy: 'Little, Brown', language: 'English',
    imageUrl: '/images/mythology-hamilton.jpg', rating: 4.5,
  },
  {
    title: 'Short Stories by Premchand',
    author: 'Munshi Premchand',
    category: 'Storytelling',
    genre: 'Hindi Short Stories',
    description: 'The finest short stories by the godfather of Hindi and Urdu literature — Idgah, Kafan, Namak ka Daroga and more.',
    price: 249, stock: 55, publishedBy: 'Rajpal & Sons', language: 'Hindi',
    imageUrl: '/images/premchand-stories.jpg', rating: 4.8,
  },

  // ── Kids Books ─────────────────────────────────────────────────────────────
  {
    title: 'The Very Hungry Caterpillar',
    author: 'Eric Carle',
    category: 'Kids',
    genre: 'Picture Book',
    description: 'The beloved classic picture book about a caterpillar\'s journey through food to become a butterfly. Perfect for ages 2-5.',
    price: 299, stock: 100, publishedBy: 'Philomel Books', language: 'English',
    imageUrl: '/images/hungry-caterpillar.jpg', rating: 4.9,
  },
  {
    title: 'Goosebumps: Say Cheese and Die!',
    author: 'R.L. Stine',
    category: 'Kids',
    genre: 'Horror for Kids',
    description: 'When Greg finds a strange camera, every picture he takes predicts a horrible event. A favourite spooky adventure for ages 8-12.',
    price: 199, stock: 80, publishedBy: 'Scholastic', language: 'English',
    imageUrl: '/images/goosebumps.jpg', rating: 4.5,
  },
  {
    title: 'Tenali Raman: The Witty Poet',
    author: 'Subba Rao (retold)',
    category: 'Kids',
    genre: 'Indian Folk Tales',
    description: 'Hilarious and wise stories of the witty court jester Tenali Raman who outwitted kings and scholars.',
    price: 149, stock: 120, publishedBy: 'Children\'s Book Trust', language: 'English',
    imageUrl: '/images/tenali-raman.jpg', rating: 4.7,
  },
  {
    title: 'Akbar and Birbal: The Wisest Tales',
    author: 'Compiled by Sudha Murty',
    category: 'Kids',
    genre: 'Indian Folk Tales',
    description: 'The beloved stories of Emperor Akbar and his witty minister Birbal that delight and educate children.',
    price: 179, stock: 100, publishedBy: 'Puffin Books India', language: 'English',
    imageUrl: '/images/akbar-birbal.jpg', rating: 4.7,
  },
  {
    title: 'Charlie and the Chocolate Factory',
    author: 'Roald Dahl',
    category: 'Kids',
    genre: 'Children\'s Fiction',
    description: 'Young Charlie Bucket wins a golden ticket and enters Willy Wonka\'s magical chocolate factory.',
    price: 249, stock: 90, publishedBy: 'Puffin Books', language: 'English',
    imageUrl: '/images/charlie-chocolate.jpg', rating: 4.8,
  },
  {
    title: 'The Jungle Book',
    author: 'Rudyard Kipling',
    category: 'Kids',
    genre: 'Children\'s Classic',
    description: 'The adventures of Mowgli the boy raised by wolves in the Indian jungle. Featuring Baloo, Bagheera, and Shere Khan.',
    price: 199, stock: 75, publishedBy: 'Macmillan', language: 'English',
    imageUrl: '/images/jungle-book.jpg', rating: 4.6,
  },
  {
    title: 'Suppandi: The Best of Tinkle',
    author: 'Tinkle Comics',
    category: 'Kids',
    genre: 'Comics',
    description: 'The funniest adventures of India\'s most lovable dimwit Suppandi from the iconic Tinkle comic magazine.',
    price: 149, stock: 150, publishedBy: 'ACK Media', language: 'English',
    imageUrl: '/images/suppandi.jpg', rating: 4.8,
  },
  {
    title: 'Amar Chitra Katha: Ramayana',
    author: 'Anant Pai',
    category: 'Kids',
    genre: 'Comics/Mythology',
    description: 'The epic story of Lord Rama beautifully illustrated in the iconic Amar Chitra Katha style. For ages 6 and above.',
    price: 199, stock: 120, publishedBy: 'ACK Media', language: 'English',
    imageUrl: '/images/amar-chitra-ramayana.jpg', rating: 4.9,
  },
  {
    title: 'The Little Prince',
    author: 'Antoine de Saint-Exupéry',
    category: 'Kids',
    genre: 'Children\'s Classic',
    description: 'A poetic tale about a young prince who visits various planets. Loved by children and adults alike.',
    price: 199, stock: 60, publishedBy: 'Wordsworth Editions', language: 'English',
    imageUrl: '/images/little-prince.jpg', rating: 4.8,
  },
  {
    title: 'Diary of a Wimpy Kid',
    author: 'Jeff Kinney',
    category: 'Kids',
    genre: 'Children\'s Fiction',
    description: 'Greg Heffley\'s hilarious illustrated diary about surviving middle school. A hugely popular series.',
    price: 299, stock: 85, publishedBy: 'Amulet Books', language: 'English',
    imageUrl: '/images/wimpy-kid.jpg', rating: 4.7,
  },
  {
    title: 'Sudha Murty\'s Grandma\'s Bag of Stories',
    author: 'Sudha Murty',
    category: 'Kids',
    genre: 'Indian Children\'s Stories',
    description: 'Grandmother Ajji\'s magical bag holds stories of kings, princesses, and clever animals. Warm Indian tales for children.',
    price: 229, stock: 100, publishedBy: 'Puffin Books India', language: 'English',
    imageUrl: '/images/grandmas-bag.jpg', rating: 4.9,
  },

  // ── Science & Technology ───────────────────────────────────────────────────
  {
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    category: 'Science',
    genre: 'Popular Science',
    description: 'An exploration of the biggest questions about the universe — from the Big Bang to black holes.',
    price: 449, stock: 30, publishedBy: 'Bantam Books', language: 'English',
    imageUrl: '/images/brief-history-time.jpg', rating: 4.7,
  },
  {
    title: 'The Code Book',
    author: 'Simon Singh',
    category: 'Science',
    genre: 'Cryptography',
    description: 'The science of secrecy from ancient Egypt to quantum cryptography.',
    price: 499, stock: 20, publishedBy: 'Fourth Estate', language: 'English',
    imageUrl: '/images/code-book.jpg', rating: 4.6,
  },
  {
    title: 'Zero to One',
    author: 'Peter Thiel',
    category: 'Technology',
    genre: 'Entrepreneurship',
    description: 'Notes on startups — how to build the future. Essential reading for founders.',
    price: 499, stock: 35, publishedBy: 'Crown Business', language: 'English',
    imageUrl: '/images/zero-to-one.jpg', rating: 4.5,
  },
  {
    title: 'The Lean Startup',
    author: 'Eric Ries',
    category: 'Technology',
    genre: 'Entrepreneurship',
    description: 'How today\'s entrepreneurs use continuous innovation to create successful businesses.',
    price: 549, stock: 30, publishedBy: 'Crown Business', language: 'English',
    imageUrl: '/images/lean-startup.jpg', rating: 4.4,
  },

  // ── Health & Wellness ──────────────────────────────────────────────────────
  {
    title: 'Why We Sleep',
    author: 'Matthew Walker',
    category: 'Health',
    genre: 'Wellness',
    description: 'Unlocking the power of sleep and dreams. A life-changing book about our most vital activity.',
    price: 499, stock: 25, publishedBy: 'Scribner', language: 'English',
    imageUrl: '/images/why-we-sleep.jpg', rating: 4.7,
  },
  {
    title: 'The Body Keeps the Score',
    author: 'Bessel van der Kolk',
    category: 'Health',
    genre: 'Mental Health',
    description: 'Brain, mind, and body in the healing of trauma. A groundbreaking work on PTSD.',
    price: 599, stock: 20, publishedBy: 'Viking', language: 'English',
    imageUrl: '/images/body-keeps-score.jpg', rating: 4.8,
  },
  {
    title: 'Eat Right for Your Type',
    author: 'Peter J. D\'Adamo',
    category: 'Health',
    genre: 'Nutrition',
    description: 'The individualized diet solution based on your blood type.',
    price: 399, stock: 30, publishedBy: 'G. P. Putnam\'s Sons', language: 'English',
    imageUrl: '/images/eat-right.jpg', rating: 3.8,
  },

  // ── Indian Literature ──────────────────────────────────────────────────────
  {
    title: 'Godan',
    author: 'Munshi Premchand',
    category: 'Indian Literature',
    genre: 'Hindi Novel',
    description: 'The masterpiece of Premchand — the story of a poor farmer\'s dream of owning a cow. A classic of Hindi literature.',
    price: 249, stock: 45, publishedBy: 'Lokbharti Prakashan', language: 'Hindi',
    imageUrl: '/images/godan.jpg', rating: 4.7,
  },
  {
    title: 'Devdas',
    author: 'Sarat Chandra Chattopadhyay',
    category: 'Indian Literature',
    genre: 'Bengali Novel',
    description: 'The tragic love story that became a cultural icon. Devdas and Paro — a tale of forbidden love and self-destruction.',
    price: 199, stock: 50, publishedBy: 'Rupa Publications', language: 'Hindi',
    imageUrl: '/images/devdas.jpg', rating: 4.4,
  },
  {
    title: 'Midnight\'s Children',
    author: 'Salman Rushdie',
    category: 'Indian Literature',
    genre: 'Magical Realism',
    description: 'Booker Prize winner — the story of children born at the moment of India\'s independence and their magical gifts.',
    price: 499, stock: 25, publishedBy: 'Jonathan Cape', language: 'English',
    imageUrl: '/images/midnights-children.jpg', rating: 4.3,
  },
  {
    title: 'A Suitable Boy',
    author: 'Vikram Seth',
    category: 'Indian Literature',
    genre: 'Indian Novel',
    description: 'One of the longest novels in the English language — a sweeping saga of post-partition India.',
    price: 699, stock: 20, publishedBy: 'HarperCollins', language: 'English',
    imageUrl: '/images/suitable-boy.jpg', rating: 4.5,
  },

  // ── Management & Leadership ────────────────────────────────────────────────
  {
    title: 'Good to Great',
    author: 'Jim Collins',
    category: 'Management',
    genre: 'Business',
    description: 'Why some companies make the leap and others don\'t. A landmark study of business excellence.',
    price: 599, stock: 25, publishedBy: 'HarperBusiness', language: 'English',
    imageUrl: '/images/good-to-great.jpg', rating: 4.5,
  },
  {
    title: 'Leaders Eat Last',
    author: 'Simon Sinek',
    category: 'Management',
    genre: 'Leadership',
    description: 'Why some teams pull together and others don\'t. A study of what makes great leaders.',
    price: 499, stock: 30, publishedBy: 'Portfolio/Penguin', language: 'English',
    imageUrl: '/images/leaders-eat-last.jpg', rating: 4.3,
  },
  {
    title: 'Start with Why',
    author: 'Simon Sinek',
    category: 'Management',
    genre: 'Leadership',
    description: 'How great leaders inspire everyone to take action. The Golden Circle concept.',
    price: 449, stock: 35, publishedBy: 'Portfolio/Penguin', language: 'English',
    imageUrl: '/images/start-with-why.jpg', rating: 4.5,
  },

  // ── Travel ─────────────────────────────────────────────────────────────────
  {
    title: 'Eat Pray Love',
    author: 'Elizabeth Gilbert',
    category: 'Travel',
    genre: 'Travel Memoir',
    description: 'A woman\'s search for everything across Italy, India, and Indonesia.',
    price: 349, stock: 30, publishedBy: 'Viking', language: 'English',
    imageUrl: '/images/eat-pray-love.jpg', rating: 4.1,
  },
  {
    title: 'Into the Wild',
    author: 'Jon Krakauer',
    category: 'Travel',
    genre: 'Adventure',
    description: 'The true story of Christopher McCandless who abandoned everything to journey into the Alaskan wilderness.',
    price: 349, stock: 25, publishedBy: 'Anchor Books', language: 'English',
    imageUrl: '/images/into-the-wild.jpg', rating: 4.5,
  },

  // ── Technology: Language & Framework Full Courses ─────────────────────────
  {
    title: 'Rapidex English Speaking Course',
    author: 'R.K. Gupta',
    category: 'Technology',
    genre: 'Language Learning',
    description: 'The most popular English-speaking course in India — covers grammar, vocabulary, conversation, and idioms for confident English communication.',
    price: 199, stock: 120, publishedBy: 'Pustak Mahal', language: 'English/Hindi',
    imageUrl: '/images/rapidex-english.jpg', rating: 4.2,
  },
  {
    title: 'Java: The Complete Reference',
    author: 'Herbert Schildt',
    category: 'Technology',
    genre: 'Programming',
    description: 'The definitive Java reference covering Java SE, APIs, frameworks, and best practices — from fundamentals to advanced enterprise features.',
    price: 799, stock: 60, publishedBy: 'McGraw-Hill', language: 'English',
    imageUrl: '/images/java-complete-reference.jpg', rating: 4.6,
  },
  {
    title: 'Python Crash Course',
    author: 'Eric Matthes',
    category: 'Technology',
    genre: 'Programming',
    description: 'A hands-on, project-based introduction to Python — the fastest way to learn Python programming through real projects.',
    price: 649, stock: 75, publishedBy: 'No Starch Press', language: 'English',
    imageUrl: '/images/python-crash-course.jpg', rating: 4.7,
  },
  {
    title: 'MongoDB: The Definitive Guide',
    author: 'Shannon Bradshaw, Eoin Brazil & Kristina Chodorow',
    category: 'Technology',
    genre: 'Database',
    description: 'The comprehensive guide to MongoDB — covers data modelling, queries, aggregation, replication, sharding, and administration.',
    price: 699, stock: 45, publishedBy: 'O\'Reilly Media', language: 'English',
    imageUrl: '/images/mongodb-guide.jpg', rating: 4.4,
  },
  {
    title: 'PostgreSQL: Up and Running',
    author: 'Regina Obe & Leo Hsu',
    category: 'Technology',
    genre: 'Database',
    description: 'A practical introduction to PostgreSQL — covers installation, data types, queries, indexing, extensions, and performance tuning.',
    price: 649, stock: 40, publishedBy: 'O\'Reilly Media', language: 'English',
    imageUrl: '/images/postgresql-guide.jpg', rating: 4.3,
  },
  {
    title: 'Learning SQL',
    author: 'Alan Beaulieu',
    category: 'Technology',
    genre: 'Database',
    description: 'Master SQL from the ground up — covers SELECT, JOINs, subqueries, transactions, stored procedures, and database design.',
    price: 549, stock: 55, publishedBy: 'O\'Reilly Media', language: 'English',
    imageUrl: '/images/learning-sql.jpg', rating: 4.4,
  },
  {
    title: 'JavaScript: The Good Parts',
    author: 'Douglas Crockford',
    category: 'Technology',
    genre: 'Programming',
    description: 'Unearthing the excellence in JavaScript — the concise guide to the best features of the language, patterns and best practices.',
    price: 449, stock: 65, publishedBy: 'O\'Reilly Media', language: 'English',
    imageUrl: '/images/javascript-good-parts.jpg', rating: 4.5,
  },
  {
    title: 'Kubernetes in Action',
    author: 'Marko Lukša',
    category: 'Technology',
    genre: 'DevOps',
    description: 'The complete guide to Kubernetes — learn to build, deploy, and manage containerised applications in production Kubernetes clusters.',
    price: 849, stock: 35, publishedBy: 'Manning Publications', language: 'English',
    imageUrl: '/images/kubernetes-in-action.jpg', rating: 4.6,
  },
  {
    title: 'Redis in Action',
    author: 'Josiah Carlson',
    category: 'Technology',
    genre: 'Database',
    description: 'Covers Redis data structures, caching, pub/sub, queuing, and real-world use cases for blazing-fast in-memory data management.',
    price: 699, stock: 30, publishedBy: 'Manning Publications', language: 'English',
    imageUrl: '/images/redis-in-action.jpg', rating: 4.3,
  },
  {
    title: 'Node.js Design Patterns',
    author: 'Mario Casciaro & Luciano Mammino',
    category: 'Technology',
    genre: 'Programming',
    description: 'Master Node.js architecture — covers async patterns, streams, creational and structural design patterns for scalable Node.js applications.',
    price: 749, stock: 40, publishedBy: 'Packt Publishing', language: 'English',
    imageUrl: '/images/nodejs-design-patterns.jpg', rating: 4.5,
  },
  {
    title: 'Django for Professionals',
    author: 'William S. Vincent',
    category: 'Technology',
    genre: 'Web Development',
    description: 'Build production-ready web applications with Django — covers Docker, PostgreSQL, authentication, REST APIs, and deployment.',
    price: 649, stock: 45, publishedBy: 'WelcomeToCode', language: 'English',
    imageUrl: '/images/django-for-beginners.jpg', rating: 4.4,
  },
  {
    title: 'Building Data Science Applications with FastAPI',
    author: 'François Voron',
    category: 'Technology',
    genre: 'Web Development',
    description: 'Build high-performance Python REST APIs and data science applications with FastAPI, Pydantic, async/await, and SQLAlchemy.',
    price: 699, stock: 35, publishedBy: 'Packt Publishing', language: 'English',
    imageUrl: '/images/fastapi-guide.jpg', rating: 4.3,
  },
  {
    title: 'Learning React',
    author: 'Alex Banks & Eve Porcello',
    category: 'Technology',
    genre: 'Web Development',
    description: 'Functional approaches to building modern React applications — covers hooks, state management, React Router, and testing.',
    price: 699, stock: 55, publishedBy: 'O\'Reilly Media', language: 'English',
    imageUrl: '/images/learning-react.jpg', rating: 4.5,
  },
  {
    title: 'Angular: Up and Running',
    author: 'Shyam Seshadri',
    category: 'Technology',
    genre: 'Web Development',
    description: 'Get productive with Angular quickly — covers components, services, routing, forms, HTTP, RxJS observables, and testing.',
    price: 749, stock: 40, publishedBy: 'O\'Reilly Media', language: 'English',
    imageUrl: '/images/angular-guide.jpg', rating: 4.2,
  },
  {
    title: 'Docker Deep Dive',
    author: 'Nigel Poulton',
    category: 'Technology',
    genre: 'DevOps',
    description: 'A fast-paced guide to Docker — covers images, containers, swarms, networking, volumes, and deploying multi-container apps.',
    price: 499, stock: 50, publishedBy: 'Independently Published', language: 'English',
    imageUrl: '/images/docker-deep-dive.jpg', rating: 4.5,
  },
  {
    title: 'Microservices Patterns',
    author: 'Chris Richardson',
    category: 'Technology',
    genre: 'Software Architecture',
    description: 'Proven patterns for building reliable microservices — covers sagas, CQRS, event sourcing, API gateways, and service discovery.',
    price: 849, stock: 30, publishedBy: 'Manning Publications', language: 'English',
    imageUrl: '/images/microservices-patterns.jpg', rating: 4.6,
  },
  {
    title: 'ChatGPT and the Future of AI',
    author: 'Sandy Carter',
    category: 'Technology',
    genre: 'Artificial Intelligence',
    description: 'Explores how ChatGPT and large language models are transforming business, creativity, and society — a guide to the AI revolution.',
    price: 499, stock: 60, publishedBy: 'McGraw-Hill', language: 'English',
    imageUrl: '/images/chatgpt-guide.jpg', rating: 4.1,
  },
  {
    title: 'Hands-On Large Language Models',
    author: 'Jay Alammar & Maarten Grootendorst',
    category: 'Technology',
    genre: 'Artificial Intelligence',
    description: 'A practical guide to working with large language models including Claude and GPT — covers prompting, fine-tuning, embeddings, RAG, and LLM applications.',
    price: 899, stock: 40, publishedBy: 'O\'Reilly Media', language: 'English',
    imageUrl: '/images/claude-guide.jpg', rating: 4.7,
  },
];

async function main() {
  console.log(`Seeding database with ${books.length} books...`);

  let created = 0;
  let updated = 0;

  for (const book of books) {
    const existing = await prisma.product.findFirst({ where: { title: book.title } });
    if (existing) {
      await prisma.product.update({ where: { id: existing.id }, data: book });
      updated++;
    } else {
      await prisma.product.create({ data: book });
      created++;
    }
  }

  const total = await prisma.product.count();
  console.log(`Done. Created: ${created}, Updated: ${updated}. Total books in DB: ${total}`);
}

main()
  .catch((err) => {
    console.error('Seed failed:', err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
